### ISSUE TITLE
binary 0.8.4.0 fails to build with bytestring 0.10.2.0

### ISSUE THREAD

**Issue by snoyberg** [kolmodin/binary#121]
I just received a [Travis build failure](https://travis-ci.org/yesodweb/authenticate/jobs/142395945) due to binary 0.8.4.0 being incompatible with bytestring 0.10.2.0, which does not provide the `Data.ByteString.Short` module:

<details>
```
Downloading binary-0.8.4.0...
Configuring binary-0.8.4.0...
Building binary-0.8.4.0...
Preprocessing library binary-0.8.4.0...
src/Data/Binary/Builder.hs:71:18:
    Could not find module `Data.ByteString.Short'
    Perhaps you meant
      Data.ByteString.Char8 (from bytestring-0.10.2.0)
      Data.ByteString.Char8 (needs flag -package bytestring-0.10.0.2)
      Data.ByteString.Lazy (needs flag -package bytestring-0.10.0.2)
    Use -v to see a list of the files searched for.
Failed to install binary-0.8.4.0
```
</details>

Would it be possible to add some lower bounds on Hackage?

**Comment by kolmodin** [comment]
Thanks for catching this! The code that uses `Data.ByteString.Shart` should be protected by CPP conditionals. This one import is not, that should be fixed.
When you use older `bytestring` that don't have `Data.ByteString.Short`, `binary` will not export these functions.

**Comment by snoyberg** [comment]
Sounds good. Personally, I don't need the functionality, my only concern is Travis builds not failing. So a CPP-protected import or a lower bound are equally fine by me.

**Comment by kolmodin** [comment]
Fixed in `binary-0.8.4.1`.

**Comment by snoyberg** [comment]
Thanks!

**Comment by michaelt** [comment]
I think there is still something wrong somewhere in here. In this run of the .travis.yml with the tests shut off https://travis-ci.org/michaelt/binary/jobs/143794594 everything passes, but ghc-7.4.2 and ghc-7.6.3 build a recent version of bytestring,  bytestring-0.10.8.1, rather than using the one that came with the compiler, which is a catastrophe in practice though it works here. The first ghc to use its own bytestring is ghc-7.8.4 which uses bytestring-0.10.4.0 I came across this problem trying to build `pipes-http` which for ghc-7.6.4 did try to build the minimal constraint bytestring-0.8.2 (again, not the bytestring that came with the compiler).  https://travis-ci.org/michaelt/Haskell-Pipes-HTTP-Library/builds/143781773 This fails with a Safe haskell error, but I think that what its doing is basically crazy anyway, building a new bytestring. I'm not sure though.

**Comment by snoyberg** [comment]
There's basically nothing that the binary package can do about that: it comes down to the cabal-install dependency solver making an arbitrary and IMO inferior install plan decision. You can probably work around it by adding something like `--constraint 'bytestring installed'` (my syntax may be a little off).

**Comment by michaelt** [comment]
Yes, I use constraints like that in my cabal.config files. What took me by surprise, once I realized that bad bytestring installs were happening, was that this already kicks in with travis' default ghc, ghc-7.6.3 - I guess from debian stable. (`pipes-http` was just using a travis.yml reading `language: haskell`) This must have been true for several months, so it seems it's not a practical issue (except with travis builds!) I guess the hygenic solution for libraries that use `binary` is to enforce 'ghc-7.8 or higher' with upper bounds on base.

**Comment by michaelt** [comment]
Maybe there is one other result, that binary should bump the bytestring constraint to bytestring-0.10.4 since it seems ghc-7.6.*  came with bytestring-0.10.0 and ghc-7.8.* all came with -0.10.4 
http://downloads.haskell.org/~ghc/7.6.3/docs/html/libraries/bytestring-0.10.0.2/index.html
https://downloads.haskell.org/~ghc/7.8.1/docs/html/libraries/bytestring-0.10.4.0/index.html Then the cpp kolmodin put in can be scrapped.

**Comment by kolmodin** [comment]
In https://travis-ci.org/michaelt/binary/jobs/143794592 the tests aren't built, but all the tests' dependencies are still installed. See line 205 in the output. Something in those dependencies depend on a newer `bytestring`, thus it won't use the one shipped with GHC.
If this trial was repeated but without installing all those deps it should use the old `bytestring`.

Your testing seems to show that `binary` would then fail to build due to Safe Haskell;
```
Configuring binary-0.8.4.1...
Building binary-0.8.4.1...
Failed to install binary-0.8.4.1
Last 10 lines of the build log ( /home/travis/.cabal/logs/binary-0.8.4.1.log ):
    Data.ByteString.Builder: Can't be safely imported!
    The module itself isn't safe.
```

So either we need to add even more CPP in order to not mark the `binary` modules as Safe when using older `bytestring`, or simply depend on a more recent `bytestring`.
The better choice would be to get rid of the CPP and depend on a more recent `bytestring`.

We don't need to depend on a more recent GHC, as long as the user installs the updated `bytestring`.

We already depend on `bytestring >= 0.10.2`. Changing that to `bytestring >= 0.10.4` should take care of the problem.
That `bytestring` was shipped with GHC 7.8.1. https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory

**Comment by michaelt** [comment]
Ah, thanks for that chart of version history, I was sort of deducing it by degrees. The bytestring 0.10.2 series never corresponded to a ghc, so ">= bytestring 0.10.2" is effectively ">= bytestring 0.10.4," if the user is to employ the bytestring that came with ghc.

The part above I don't get is "We don't need to depend on a more recent GHC, as long as the user installs the updated bytestring". I was working with the idea that it's bad policy to work with 2 versions of bytestring, one installed and one a ghc boot library,  unless you are up to something pretty technical like developing bytestring itself. It *can* work out of course. Maybe this is an out of date piece of wisdom?

In any case, an increase to  ">= bytestring 0.10.4"  will stop the specific failure we see with `pipes-http` + ghc-7.6

**Comment by kolmodin** [comment]
`binary-0.8.4.1.` only fixed part of the problem. The rest was fixed with https://github.com/kolmodin/binary/issues/123. The affected versions on hackage should be fixed by now too.
