### ISSUE TITLE
binary fails to build with older bytestring

### ISSUE THREAD

**Issue by kolmodin** [kolmodin/binary#123]
See discussion #121. `binary` fails to build with older `bytestring` due to missing Safe Haskell declarations in the older `bytestring` versions.

**Comment by sol** [comment]
From what I tried, the last three releases of `binary` are affected by this: `0.8.3.0`, `0.8.4.0` and `0.8.4.1`

I assume this can be fixed by adjusting the lower bound of `bytestring` to `bytestring >=0.10.4` for all the three affected version of `binary` on Hackage.

This is critical, as currently `QuickCheck` does not build on the default Travis Haskell infrastructure.

see: https://github.com/nick8325/quickcheck/issues/154 https://github.com/hspec/hspec-example/pull/10

**Comment by sol** [comment]
See https://github.com/haskell-infra/hackage-trustees/issues/91

**Comment by kolmodin** [comment]
Yes, this needs to be done retroactively on hackage, and in this repository for future releases.

**Comment by Gabriel439** [comment]
I just ran into this issue today, too

**Comment by kolmodin** [comment]
I'm working on fixing it right now.
I'm surprised that such old bytestring versions are still used.

**Comment by kolmodin** [comment]
Fixed. Also fixed on hackage, `0.8.3.0`, `0.8.4.0` and `0.8.4.1`.
