### ISSUE TITLE
Add GHC-8.2 to CI

### ISSUE THREAD

**Issue by treeowl** [kolmodin/binary#142]
Travis should be testing against GHC-8.2 now that it's been released.

**Comment by kolmodin** [comment]
Yes, I agree. The travis build is failing at the moment due to failing to install the dependencies. Unfortunately it's complicated to compile libaries like `binary` due to circular dependencies :/

Could you make a PR for adding GHC-8.2 to Travis? It probably won't build properly due to the deps, but it's a start.
